onlyBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-free'
  - '@fortawesome/free-brands-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - '@parcel/watcher'
  - core-js
  - deasync
  - es5-ext
  - esbuild
  - svelte-preprocess
